-- MySQL Script generated by MySQL Workbench
-- Mon Mar 11 13:49:28 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET
  @OLD_UNIQUE_CHECKS = @ @UNIQUE_CHECKS,
  UNIQUE_CHECKS = 0;

SET
  @OLD_FOREIGN_KEY_CHECKS = @ @FOREIGN_KEY_CHECKS,
  FOREIGN_KEY_CHECKS = 0;

SET
  @OLD_SQL_MODE = @ @SQL_MODE,
  SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema voterdb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema voterdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `voterdb` DEFAULT CHARACTER SET utf8;

USE `voterdb`;

-- -----------------------------------------------------
-- Table `voterdb`.`occupation_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`occupation_status` (
  `occupation_status_id` INT NOT NULL,
  `occupation_status_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`occupation_status_id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`person` (
  `idperson` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `DOB` DATETIME NULL,
  `occupation_status` INT NULL,
  `voter_id` INT NULL,
  PRIMARY KEY (`idperson`),
  INDEX `p_occupation_status_id_idx` (`occupation_status` ASC) VISIBLE,
  CONSTRAINT `p_occupation_status_id` FOREIGN KEY (`occupation_status`) REFERENCES `voterdb`.`occupation_status` (`occupation_status_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`state` (
  `idstate` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idstate`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`city` (
  `idcity` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `state` INT NULL,
  PRIMARY KEY (`idcity`),
  INDEX `cit_state_idx` (`state` ASC) VISIBLE,
  CONSTRAINT `cit_state` FOREIGN KEY (`state`) REFERENCES `voterdb`.`state` (`idstate`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`neighborhood`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`neighborhood` (
  `idneighborhood` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `city` INT NULL,
  `geographicalBoundaries` VARCHAR(45) NULL,
  PRIMARY KEY (`idneighborhood`),
  INDEX `nbhd_city_idx` (`city` ASC) VISIBLE,
  CONSTRAINT `nbhd_city` FOREIGN KEY (`city`) REFERENCES `voterdb`.`city` (`idcity`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`address` (
  `idaddress` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NULL,
  `country` INT NULL,
  `zip` INT NULL,
  `neighborhood` INT NULL,
  PRIMARY KEY (`idaddress`),
  INDEX `addr_neighborhood_idx` (`neighborhood` ASC) VISIBLE,
  CONSTRAINT `addr_neighborhood` FOREIGN KEY (`neighborhood`) REFERENCES `voterdb`.`neighborhood` (`idneighborhood`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`election_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`election_type` (
  `idelection_type` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idelection_type`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`election`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`election` (
  `idelection` INT NOT NULL AUTO_INCREMENT,
  `dateOfElection` DATETIME NULL,
  `type` INT NULL,
  PRIMARY KEY (`idelection`),
  INDEX `el_type_id_idx` (`type` ASC) VISIBLE,
  CONSTRAINT `el_type_id` FOREIGN KEY (`type`) REFERENCES `voterdb`.`election_type` (`idelection_type`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`districtDesignationLookup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`districtDesignationLookup` (
  `iddistrictDesignationLookup` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`iddistrictDesignationLookup`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`district`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`district` (
  `iddistrict` INT NOT NULL AUTO_INCREMENT,
  `district_number` INT NULL,
  `neighborhood` INT NULL,
  `designation_id` INT NULL,
  `population` INT NULL,
  `total_reg_voters` INT NULL,
  `geographical_boundary_id` INT NULL,
  PRIMARY KEY (`iddistrict`),
  INDEX `dist_neighborhood_idx` (`neighborhood` ASC) VISIBLE,
  INDEX `dist_designation_id_idx` (`designation_id` ASC) VISIBLE,
  CONSTRAINT `dist_neighborhood` FOREIGN KEY (`neighborhood`) REFERENCES `voterdb`.`neighborhood` (`idneighborhood`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `dist_designation_id` FOREIGN KEY (`designation_id`) REFERENCES `voterdb`.`districtDesignationLookup` (`iddistrictDesignationLookup`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`ballot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`ballot` (
  `idballot` INT NOT NULL AUTO_INCREMENT,
  `election` INT NULL,
  `district` INT NULL,
  PRIMARY KEY (`idballot`),
  INDEX `bal_election_id_idx` (`election` ASC) VISIBLE,
  INDEX `bal_district_id_idx` (`district` ASC) VISIBLE,
  CONSTRAINT `bal_election_id` FOREIGN KEY (`election`) REFERENCES `voterdb`.`election` (`idelection`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `bal_district_id` FOREIGN KEY (`district`) REFERENCES `voterdb`.`district` (`iddistrict`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`voter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`voter` (
  `idvoter` INT NOT NULL,
  `registrationID` VARCHAR(45) NULL,
  `registrationDate` DATETIME NULL,
  PRIMARY KEY (`idvoter`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`deviceMake`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`deviceMake` (
  `iddeviceMake` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`iddeviceMake`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`deviceModel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`deviceModel` (
  `iddeviceModel` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `deviceMake` INT NULL,
  PRIMARY KEY (`iddeviceModel`),
  INDEX `devm_make_idx` (`deviceMake` ASC) VISIBLE,
  CONSTRAINT `devm_make` FOREIGN KEY (`deviceMake`) REFERENCES `voterdb`.`deviceMake` (`iddeviceMake`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`device` (
  `iddevice` INT NOT NULL AUTO_INCREMENT,
  `deviceModel` INT NULL,
  `ipaddress` VARCHAR(45) NULL,
  PRIMARY KEY (`iddevice`),
  INDEX `dev_model_idx` (`deviceModel` ASC) VISIBLE,
  CONSTRAINT `dev_model` FOREIGN KEY (`deviceModel`) REFERENCES `voterdb`.`deviceModel` (`iddeviceModel`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`voterBallot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`voterBallot` (
  `idvoterBallot` INT NOT NULL AUTO_INCREMENT,
  `ballot` INT NULL,
  `voter` INT NULL,
  `submissionDate` DATETIME NULL,
  `status` VARCHAR(45) NULL,
  `device` INT NULL,
  PRIMARY KEY (`idvoterBallot`),
  INDEX `vb_ballot_id_idx` (`ballot` ASC) VISIBLE,
  INDEX `vb_voter_id_idx` (`voter` ASC) VISIBLE,
  INDEX `vb_device_idx` (`device` ASC) VISIBLE,
  CONSTRAINT `vb_ballot_id` FOREIGN KEY (`ballot`) REFERENCES `voterdb`.`ballot` (`idballot`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `vb_voter_id` FOREIGN KEY (`voter`) REFERENCES `voterdb`.`voter` (`idvoter`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `vb_device` FOREIGN KEY (`device`) REFERENCES `voterdb`.`device` (`iddevice`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`contest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`contest` (
  `idcontest` INT NOT NULL AUTO_INCREMENT,
  `ballot` INT NULL,
  PRIMARY KEY (`idcontest`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`measure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`measure` (
  `idmeasure` INT NOT NULL AUTO_INCREMENT,
  `idballot` INT NULL,
  PRIMARY KEY (`idmeasure`),
  INDEX `mes_ballot_id_idx` (`idballot` ASC) VISIBLE,
  CONSTRAINT `mes_ballot_id` FOREIGN KEY (`idballot`) REFERENCES `voterdb`.`ballot` (`idballot`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`candidate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`candidate` (
  `idcandidate` INT NOT NULL AUTO_INCREMENT,
  `person` INT NULL,
  `district` INT NULL,
  PRIMARY KEY (`idcandidate`),
  INDEX `cand_person_id_idx` (`person` ASC) VISIBLE,
  INDEX `cand_district_id_idx` (`district` ASC) VISIBLE,
  CONSTRAINT `cand_person_id` FOREIGN KEY (`person`) REFERENCES `voterdb`.`person` (`idperson`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `cand_district_id` FOREIGN KEY (`district`) REFERENCES `voterdb`.`district` (`iddistrict`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`party`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`party` (
  `idparty` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idparty`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`gender` (
  `idgender` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idgender`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`personGender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`personGender` (
  `idpersonGender` INT NOT NULL AUTO_INCREMENT,
  `person` INT NULL,
  `gender` INT NULL,
  PRIMARY KEY (`idpersonGender`),
  INDEX `pg_person_idx` (`person` ASC) VISIBLE,
  INDEX `pg_gender_idx` (`gender` ASC) VISIBLE,
  CONSTRAINT `pg_person` FOREIGN KEY (`person`) REFERENCES `voterdb`.`person` (`idperson`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `pg_gender` FOREIGN KEY (`gender`) REFERENCES `voterdb`.`gender` (`idgender`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`ballotSubmitted`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`ballotSubmitted` (
  `idballotSubmitted` INT NOT NULL,
  `ballot` INT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`idballotSubmitted`),
  INDEX `bsub_ballot_id_idx` (`ballot` ASC) VISIBLE,
  CONSTRAINT `bsub_ballot_id` FOREIGN KEY (`ballot`) REFERENCES `voterdb`.`ballot` (`idballot`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`voterRegistered`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`voterRegistered` (
  `idvoterRegistered` INT NOT NULL,
  `voter` INT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`idvoterRegistered`),
  INDEX `vreg_voter_id_idx` (`voter` ASC) VISIBLE,
  CONSTRAINT `vreg_voter_id` FOREIGN KEY (`voter`) REFERENCES `voterdb`.`voter` (`idvoter`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`country` (
  `country_id` INT NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(45) NOT NULL,
  `country_code` INT NULL DEFAULT NULL,
  PRIMARY KEY (`country_id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `voterdb`.`degree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`degree` (
  `iddegree` INT NOT NULL AUTO_INCREMENT,
  `degree_name` VARCHAR(45) NULL,
  PRIMARY KEY (`iddegree`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`person_edu_degree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`person_edu_degree` (
  `person_edu_degree_id` INT NOT NULL AUTO_INCREMENT,
  `degree` INT NULL DEFAULT NULL,
  `completion_date` DATETIME NULL,
  `person_id` INT NULL,
  PRIMARY KEY (`person_edu_degree_id`),
  INDEX `ed_deg_person_id_idx` (`person_id` ASC) VISIBLE,
  INDEX `ed_deg_degree_id_idx` (`degree` ASC) VISIBLE,
  CONSTRAINT `ed_deg_person_id` FOREIGN KEY (`person_id`) REFERENCES `voterdb`.`person` (`idperson`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ed_deg_degree_id` FOREIGN KEY (`degree`) REFERENCES `voterdb`.`degree` (`iddegree`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`gender_lookup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`gender_lookup` (
  `gender_code` INT NOT NULL AUTO_INCREMENT,
  `gender_id` INT NULL DEFAULT NULL,
  `gender_abbr` VARCHAR(45) NULL DEFAULT NULL,
  INDEX `gl_gender_id_idx` (`gender_id` ASC) VISIBLE,
  PRIMARY KEY (`gender_code`),
  CONSTRAINT `gdr_lookup` FOREIGN KEY (`gender_id`) REFERENCES `voterdb`.`gender` (`idgender`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`social_platform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`social_platform` (
  `social_platform_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`social_platform_id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `voterdb`.`SM_data_feed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`SM_data_feed` (
  `data_feed_id` INT NOT NULL AUTO_INCREMENT,
  `SMUID` INT NULL DEFAULT NULL,
  `event_id` INT NULL DEFAULT NULL,
  `evcatcodes` VARCHAR(45) NULL DEFAULT NULL,
  `timeonevent` VARCHAR(45) NULL DEFAULT NULL,
  `ip_address` VARCHAR(45) NULL DEFAULT NULL,
  `location` VARCHAR(45) NULL DEFAULT NULL,
  `device` VARCHAR(400) NULL DEFAULT NULL,
  `mentions` VARCHAR(400) NULL DEFAULT NULL,
  `hashtags` VARCHAR(400) NULL DEFAULT NULL,
  `content` VARCHAR(400) NULL DEFAULT NULL,
  PRIMARY KEY (`data_feed_id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`social_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`social_account` (
  `social_account_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `person_id` INT NULL DEFAULT NULL,
  `social_platform_id` INT NULL DEFAULT NULL,
  `SMUID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`social_account_id`),
  INDEX `person_id_idx` (`person_id` ASC) VISIBLE,
  INDEX `platform_id_idx` (`social_platform_id` ASC) VISIBLE,
  INDEX `sa_SMUID_idx` (`SMUID` ASC) VISIBLE,
  CONSTRAINT `sa_platform_id` FOREIGN KEY (`social_platform_id`) REFERENCES `voterdb`.`social_platform` (`social_platform_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `sa_SMUID` FOREIGN KEY (`SMUID`) REFERENCES `voterdb`.`SM_data_feed` (`SMUID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `voterdb`.`device_make`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`device_make` (
  `device_make_id` INT NOT NULL AUTO_INCREMENT,
  `make_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`device_make_id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `voterdb`.`device_model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`device_model` (
  `device_model_id` INT NOT NULL AUTO_INCREMENT,
  `make_id` INT NULL DEFAULT NULL,
  `model_name` VARCHAR(45) NULL DEFAULT NULL,
  `model_year` YEAR(4) NULL DEFAULT NULL,
  PRIMARY KEY (`device_model_id`),
  INDEX `dm_make_id_idx` (`make_id` ASC) VISIBLE,
  CONSTRAINT `dm_make_id` FOREIGN KEY (`make_id`) REFERENCES `voterdb`.`device_make` (`device_make_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `voterdb`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`email` (
  `email_id` INT NOT NULL AUTO_INCREMENT,
  `person_id` INT NULL DEFAULT NULL,
  `email_address` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`email_id`),
  INDEX `e_person_id_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `em_person_id` FOREIGN KEY (`person_id`) REFERENCES `voterdb`.`person` (`idperson`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `voterdb`.`event_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`event_type` (
  `event_type_id` INT NOT NULL AUTO_INCREMENT,
  `event_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`event_type_id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`location` (
  `location_id` INT NOT NULL AUTO_INCREMENT,
  `location_name` VARCHAR(45) NULL DEFAULT NULL,
  `social_account_id` INT NULL DEFAULT NULL,
  `city_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`location_id`),
  INDEX `location_SA_fk_idx` (`social_account_id` ASC) VISIBLE,
  INDEX `location_city_fk_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `location_SA_fk` FOREIGN KEY (`social_account_id`) REFERENCES `voterdb`.`social_account` (`social_account_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `location_city_id` FOREIGN KEY (`city_id`) REFERENCES `voterdb`.`city` (`idcity`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`ip_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`ip_address` (
  `ip_address_id` INT NOT NULL AUTO_INCREMENT,
  `ip_address` VARCHAR(45) NULL DEFAULT NULL,
  `location_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ip_address_id`),
  INDEX `ip_location_fk_idx` (`location_id` ASC) INVISIBLE,
  CONSTRAINT `ip_location_fk` FOREIGN KEY (`location_id`) REFERENCES `voterdb`.`location` (`location_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`device_event_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`device_event_log` (
  `device_event_id` INT NOT NULL AUTO_INCREMENT,
  `device_id` INT NULL DEFAULT NULL,
  `event_time` DATETIME NOT NULL,
  `ip_address_id` INT NULL DEFAULT NULL,
  `event_type_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`device_event_id`),
  INDEX `li_device_id_idx` (`device_id` ASC) VISIBLE,
  INDEX `event_type_idx` (`event_type_id` ASC) VISIBLE,
  INDEX `event_log_ip_idx` (`ip_address_id` ASC) VISIBLE,
  CONSTRAINT `event_type_log` FOREIGN KEY (`event_type_id`) REFERENCES `voterdb`.`event_type` (`event_type_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `event_log_ip` FOREIGN KEY (`ip_address_id`) REFERENCES `voterdb`.`ip_address` (`ip_address_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `event_log_device` FOREIGN KEY (`device_id`) REFERENCES `voterdb`.`device` (`iddevice`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `voterdb`.`phone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`phone` (
  `phone_id` INT NOT NULL AUTO_INCREMENT,
  `person_id` INT NULL DEFAULT NULL,
  `country_code` INT NULL DEFAULT NULL,
  `phone_num` INT NULL DEFAULT NULL,
  PRIMARY KEY (`phone_id`),
  INDEX `p_person_id_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `ph_person_id` FOREIGN KEY (`person_id`) REFERENCES `voterdb`.`person` (`idperson`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `voterdb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  `recurring` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `voterdb`.`purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`purchase` (
  `purchase_id` INT NOT NULL AUTO_INCREMENT,
  `event_time` DATETIME NULL DEFAULT NULL,
  `seller_acc_id` INT NULL DEFAULT NULL,
  `buyer_acc_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`purchase_id`),
  INDEX `pur_buyer_id_idx` (`buyer_acc_id` ASC) VISIBLE,
  INDEX `pur_seller_id_idx` (`seller_acc_id` ASC) VISIBLE,
  CONSTRAINT `pur_buyer_id` FOREIGN KEY (`buyer_acc_id`) REFERENCES `voterdb`.`social_account` (`social_account_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `pur_seller_id` FOREIGN KEY (`seller_acc_id`) REFERENCES `voterdb`.`social_account` (`social_account_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `voterdb`.`purchase_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`purchase_products` (
  `purchase_products_id` INT NOT NULL AUTO_INCREMENT,
  `qty` INT NULL DEFAULT NULL,
  `product_id` INT NULL DEFAULT NULL,
  `purchase_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`purchase_products_id`),
  INDEX `pp_product_id_idx` (`product_id` ASC) VISIBLE,
  INDEX `pp_purchase_id_idx` (`purchase_id` ASC) VISIBLE,
  CONSTRAINT `pp_product_id` FOREIGN KEY (`product_id`) REFERENCES `voterdb`.`product` (`product_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `pp_purchase_id` FOREIGN KEY (`purchase_id`) REFERENCES `voterdb`.`purchase` (`purchase_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `voterdb`.`event_nature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`event_nature` (
  `event_nature_id` INT NOT NULL AUTO_INCREMENT,
  `event_nature_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`event_nature_id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`social_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`social_event` (
  `social_event_id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NULL DEFAULT NULL,
  `content` VARCHAR(400) NULL DEFAULT NULL,
  `event_time` DATETIME NULL DEFAULT NULL,
  `event_type_id` INT NULL DEFAULT NULL,
  `event_nature_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`social_event_id`),
  INDEX `sp_account_id_idx` (`account_id` ASC) VISIBLE,
  INDEX `event_type_idx` (`event_type_id` ASC) VISIBLE,
  INDEX `event_nature_idx` (`event_nature_id` ASC) VISIBLE,
  CONSTRAINT `sp_account_id` FOREIGN KEY (`account_id`) REFERENCES `voterdb`.`social_account` (`social_account_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `event_type_social` FOREIGN KEY (`event_type_id`) REFERENCES `voterdb`.`event_type` (`event_type_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `event_nature` FOREIGN KEY (`event_nature_id`) REFERENCES `voterdb`.`event_nature` (`event_nature_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `voterdb`.`political_party`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`political_party` (
  `political_party_id` INT NOT NULL AUTO_INCREMENT,
  `party_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`political_party_id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`occupation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`occupation` (
  `occupation_id` INT NOT NULL,
  `person_id` INT NULL DEFAULT NULL,
  `occupation_name` VARCHAR(45) NULL DEFAULT NULL,
  `occupation_status_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`occupation_id`),
  INDEX `person_occupation_idx` (`person_id` ASC) VISIBLE,
  INDEX `occupation_status_idx` (`occupation_status_id` ASC) VISIBLE,
  CONSTRAINT `occupation_status` FOREIGN KEY (`occupation_status_id`) REFERENCES `voterdb`.`occupation_status` (`occupation_status_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`hashtags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`hashtags` (
  `hashtag_id` INT NOT NULL AUTO_INCREMENT,
  `hashtag_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`hashtag_id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`political_affiliation_lookup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`political_affiliation_lookup` (
  `affialiation_code` INT NOT NULL,
  `political_party_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`affialiation_code`),
  INDEX `pal_political_party_idx` (`political_party_id` ASC) VISIBLE,
  CONSTRAINT `pal_political_party` FOREIGN KEY (`political_party_id`) REFERENCES `voterdb`.`political_party` (`political_party_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`view_intensity_lookup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`view_intensity_lookup` (
  `intensity_code` INT NOT NULL,
  `intensity_nickname` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`intensity_code`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`political_preference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`political_preference` (
  `political_preference_id` INT NOT NULL AUTO_INCREMENT,
  `person_id` INT NULL DEFAULT NULL,
  `political_affiliation_code` INT NULL DEFAULT NULL,
  `intensity` INT NULL DEFAULT NULL,
  `event_time` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`political_preference_id`),
  INDEX `ppref_person_id_idx` (`person_id` ASC) VISIBLE,
  INDEX `ppref_political_party_id_idx` (`political_affiliation_code` ASC) VISIBLE,
  INDEX `ppref_intensity_level_idx` (`intensity` ASC) VISIBLE,
  CONSTRAINT `ppref_political_party_id` FOREIGN KEY (`political_affiliation_code`) REFERENCES `voterdb`.`political_affiliation_lookup` (`affialiation_code`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ppref_intensity_level` FOREIGN KEY (`intensity`) REFERENCES `voterdb`.`view_intensity_lookup` (`intensity_code`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ppref_person_id` FOREIGN KEY (`person_id`) REFERENCES `voterdb`.`person` (`idperson`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`religion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`religion` (
  `religion_id` INT NOT NULL AUTO_INCREMENT,
  `religion_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`religion_id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`religious_affiliation_lookup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`religious_affiliation_lookup` (
  `affiliation_code` INT NOT NULL AUTO_INCREMENT,
  `religion_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`affiliation_code`),
  INDEX `ral_religion_id_idx` (`religion_id` ASC) VISIBLE,
  CONSTRAINT `ral_religion_id` FOREIGN KEY (`religion_id`) REFERENCES `voterdb`.`religion` (`religion_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`religious_identity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`religious_identity` (
  `religious_identity_id` INT NOT NULL AUTO_INCREMENT,
  `person_id` INT NULL DEFAULT NULL,
  `affiliation_lookup_code` INT NULL DEFAULT NULL,
  `intensity` INT NULL DEFAULT NULL,
  `timestamp` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`religious_identity_id`),
  INDEX `ppref_person_id_idx` (`person_id` ASC) VISIBLE,
  INDEX `ri_affiliation_lookup_code_idx` (`affiliation_lookup_code` ASC) VISIBLE,
  INDEX `ri_intensity_id_idx` (`intensity` ASC) VISIBLE,
  CONSTRAINT `ri_affiliation_lookup_code` FOREIGN KEY (`affiliation_lookup_code`) REFERENCES `voterdb`.`religious_affiliation_lookup` (`affiliation_code`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ri_intensity_id` FOREIGN KEY (`intensity`) REFERENCES `voterdb`.`view_intensity_lookup` (`intensity_code`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ri_person_id` FOREIGN KEY (`person_id`) REFERENCES `voterdb`.`person` (`idperson`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`social_issue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`social_issue` (
  `social_issue_id` INT NOT NULL AUTO_INCREMENT,
  `social_issue_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`social_issue_id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`social_issue_lookup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`social_issue_lookup` (
  `social_issue_code` INT NOT NULL,
  `social_issue_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`social_issue_code`),
  INDEX `sia_social_issue_id_idx` (`social_issue_id` ASC) VISIBLE,
  CONSTRAINT `sia_social_issue_id` FOREIGN KEY (`social_issue_id`) REFERENCES `voterdb`.`social_issue` (`social_issue_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`social_issue_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`social_issue_view` (
  `social_issue_view_id` INT NOT NULL,
  `person_id` INT NULL DEFAULT NULL,
  `social_issue_lookup_code` INT NULL DEFAULT NULL,
  `intensity_code` INT NULL DEFAULT NULL,
  `event_time` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`social_issue_view_id`),
  INDEX `siv_person_id_idx` (`person_id` ASC) VISIBLE,
  INDEX `siv_social_issue_lookup_code_idx` (`social_issue_lookup_code` ASC) VISIBLE,
  INDEX `siv_intensity_id_idx` (`intensity_code` ASC) VISIBLE,
  CONSTRAINT `siv_social_issue_lookup_code` FOREIGN KEY (`social_issue_lookup_code`) REFERENCES `voterdb`.`social_issue_lookup` (`social_issue_code`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `siv_intensity_id` FOREIGN KEY (`intensity_code`) REFERENCES `voterdb`.`view_intensity_lookup` (`intensity_code`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `siv_person_id` FOREIGN KEY (`person_id`) REFERENCES `voterdb`.`person` (`idperson`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`social_mate_preference_lookup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`social_mate_preference_lookup` (
  `person_id` INT NOT NULL,
  `smp_attribute` VARCHAR(45) NOT NULL,
  `preference` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`person_id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`advertisement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`advertisement` (
  `advertisement_id` INT NOT NULL AUTO_INCREMENT,
  `advertisement_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`advertisement_id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`ad_clicked`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`ad_clicked` (
  `ad_clicked_id` INT NOT NULL AUTO_INCREMENT,
  `advertisement_id` INT NULL DEFAULT NULL,
  `social_account_id` INT NULL DEFAULT NULL,
  `event_time` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ad_clicked_id`),
  INDEX `ac_social_account_id_idx` (`social_account_id` ASC) VISIBLE,
  INDEX `ac_advertisement_id_idx` (`advertisement_id` ASC) VISIBLE,
  CONSTRAINT `ac_social_account_id` FOREIGN KEY (`social_account_id`) REFERENCES `voterdb`.`social_account` (`social_account_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ac_advertisement_id` FOREIGN KEY (`advertisement_id`) REFERENCES `voterdb`.`advertisement` (`advertisement_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`social_action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`social_action` (
  `social_action_id` INT NOT NULL AUTO_INCREMENT,
  `social_account_id` INT NULL DEFAULT NULL,
  `social_event_id` INT NULL DEFAULT NULL,
  `event_type_id` INT NULL DEFAULT NULL,
  `content` VARCHAR(400) NULL DEFAULT NULL,
  `event_time` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`social_action_id`),
  INDEX `saccount_FK_idx` (`social_account_id` ASC) VISIBLE,
  INDEX `sevent_FK_idx` (`social_event_id` ASC) VISIBLE,
  INDEX `seventtype_FK_idx` (`event_type_id` ASC) VISIBLE,
  CONSTRAINT `saccount_FK` FOREIGN KEY (`social_account_id`) REFERENCES `voterdb`.`social_account` (`social_account_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `sevent_FK` FOREIGN KEY (`social_event_id`) REFERENCES `voterdb`.`social_event` (`social_event_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `seventtype_FK` FOREIGN KEY (`event_type_id`) REFERENCES `voterdb`.`event_type` (`event_type_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`event_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`event_tag` (
  `event_tag_id` INT NOT NULL AUTO_INCREMENT,
  `social_event_id` INT NULL DEFAULT NULL,
  `hashtag_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`event_tag_id`),
  INDEX `even_tag_FK_idx` (`social_event_id` ASC) VISIBLE,
  INDEX `hashtag_FK_idx` (`hashtag_id` ASC) VISIBLE,
  CONSTRAINT `even_tag_FK` FOREIGN KEY (`social_event_id`) REFERENCES `voterdb`.`social_event` (`social_event_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `hashtag_FK` FOREIGN KEY (`hashtag_id`) REFERENCES `voterdb`.`hashtags` (`hashtag_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`ballotMeasureOption`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`ballotMeasureOption` (
  `idballotMeasureOption` INT NOT NULL AUTO_INCREMENT,
  `option_value` VARCHAR(45) NULL,
  `measure_id` INT NULL,
  `total_votes` INT NULL,
  PRIMARY KEY (`idballotMeasureOption`),
  INDEX `bmo_measure_id_idx` (`measure_id` ASC) VISIBLE,
  CONSTRAINT `bmo_measure_id` FOREIGN KEY (`measure_id`) REFERENCES `voterdb`.`measure` (`idmeasure`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`position` (
  `idposition` INT NOT NULL AUTO_INCREMENT,
  `position_name` INT NULL,
  `term_limit` INT NULL,
  PRIMARY KEY (`idposition`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`contestCandidate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`contestCandidate` (
  `idcontestCandidate` INT NOT NULL AUTO_INCREMENT,
  `contest_id` INT NULL,
  `position_id` INT NULL,
  `total_votes` INT NULL,
  PRIMARY KEY (`idcontestCandidate`),
  INDEX `ccand_position_id_idx` (`position_id` ASC) VISIBLE,
  INDEX `ccand_contest_id_idx` (`contest_id` ASC) VISIBLE,
  CONSTRAINT `ccand_position_id` FOREIGN KEY (`position_id`) REFERENCES `voterdb`.`position` (`idposition`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ccand_contest_id` FOREIGN KEY (`contest_id`) REFERENCES `voterdb`.`contest` (`idcontest`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`officeHeld`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`officeHeld` (
  `idofficeHeld` INT NOT NULL AUTO_INCREMENT,
  `position_id` INT NULL,
  `candidate_id` INT NULL,
  `party_id` INT NULL,
  `start_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  `district_id` INT NULL,
  PRIMARY KEY (`idofficeHeld`),
  INDEX `oh_position_id_idx` (`position_id` ASC) VISIBLE,
  INDEX `oh_candidate_id_idx` (`candidate_id` ASC) VISIBLE,
  INDEX `oh_party_id_idx` (`party_id` ASC) VISIBLE,
  INDEX `oh_district_id_idx` (`district_id` ASC) VISIBLE,
  CONSTRAINT `oh_position_id` FOREIGN KEY (`position_id`) REFERENCES `voterdb`.`position` (`idposition`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `oh_candidate_id` FOREIGN KEY (`candidate_id`) REFERENCES `voterdb`.`candidate` (`idcandidate`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `oh_party_id` FOREIGN KEY (`party_id`) REFERENCES `voterdb`.`party` (`idparty`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `oh_district_id` FOREIGN KEY (`district_id`) REFERENCES `voterdb`.`district` (`iddistrict`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `voterdb`.`voterDataFeed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voterdb`.`voterDataFeed` (
  `idvoterDataFeed` INT NOT NULL AUTO_INCREMENT,
  `ballot_id` INT NULL,
  `person_id` INT NULL,
  `device_id` INT NULL,
  `ip_address` VARCHAR(45) NULL,
  `other_data` VARCHAR(45) NULL,
  PRIMARY KEY (`idvoterDataFeed`),
  INDEX `vdf_ballot_id_idx` (`ballot_id` ASC) VISIBLE,
  INDEX `vdf_person_id_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `vdf_ballot_id` FOREIGN KEY (`ballot_id`) REFERENCES `voterdb`.`ballot` (`idballot`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `vdf_person_id` FOREIGN KEY (`person_id`) REFERENCES `voterdb`.`person` (`idperson`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

SET
  SQL_MODE = @OLD_SQL_MODE;

SET
  FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;

SET
  UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;